### ISSUE TITLE
question for heapspray

### ISSUE THREAD

**Issue by dodaeche** [unamer/vmware_escape#4]
Hi. First, thanks for your post. I have learning exploitation from your code.
In your code, There are  heap spray code with size of 0xA0, 0x90, 0xA8. 
The target object(DnD or CP) size is 0xA8, so I think it's sufficient with just spraying chunk size of 0xA8.
Maybe I'm lacking something. Is there any reason that you made chunk size of 0xA0 and 0x90 ?
Thanks for your code and wiki.

**Comment by unamer** [comment]
Hi @dodaeche 

Well, that's why the exploit isn't reliable.

> There are heap spray code with size of 0xA0, 0x90, 0xA8

Windows LFH is so annoying that If I only spray with size 0xa8, the "pwn" rate is far more lower than spraying these 3 sizes.( Actually I don't know why )

I try to make the exploit more stable and heap layout more predictable, and finally I found these sizes, as you see in code, the weird size...

However with these weird size sprayed, I can only get about 30% successful rate, too bad.

If you could find a way to control heap layout and achieve stable exploitation , pls contact me :), thanks

Sorry for my poor English ,haha.

**Comment by unamer** [comment]
Thanks for the document bro.I'm noob at heap spray.
